name: Generate Book

on:
  push:
    paths:
      - 'book/src/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Book version'
        required: false
        default: 'SNAPSHOT'

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-fonts-extra
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Generate book version
        id: version
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ] && [ "${{ github.event.inputs.version }}" != "SNAPSHOT" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +'%Y.%m.%d')-SNAPSHOT" >> $GITHUB_ENV
          fi
          
      - name: Generate book
        run: npm run build-book -- --version "${{ env.VERSION }}"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: book-files-${{ env.VERSION }}
          path: |
            book/generated/scala-zio-book-${{ env.VERSION }}.pdf
            book/generated/scala-zio-book-${{ env.VERSION }}.epub